version: '3'

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
    - ./postgres:/var/lib/postgresql/data
    networks:
    - t_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: .env
    ports:
    - "8080:80"
    volumes:
    - ./pgadmin:/var/lib/pgadmin
    - ./pgadmin_server.json:/pgadmin4/servers.json
    networks:
    - t_network

  backend:
    container_name: backend
    build: ./back
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    networks:
    - t_network
    env_file: .env

  frontend:
    container_name: frontend
    ports:
      - "8081:8080"
    build: ./front
    restart: always
    networks:
    - t_network

networks:
  t_network:

